workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Build ipa
        script: |
          xcode-project use-workspace
          xcode-project build-ipa --export-method ad-hoc
    artifacts:
      - build/ios/ipa/*.ipa